# Generated by Django 6.1.1 on 2026-10-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('author', models.TextField(blank=True, verbose_name='autor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cena')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stan magazynowy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='bib.category', verbose_name='kategoria')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
                'ordering': ['name'],
            },
        ),
    ]
