# Generated by Django 6.1.1 on 2026-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author2',
            field=models.TextField(blank=True, verbose_name='autor2'),
        ),
    ]
