# Generated by Django 6.1.1 on 2026-10-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0003_remove_product_author2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
