# Generated by Django 6.1.1 on 2026-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0004_remove_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.TextField(blank=True, verbose_name='autor'),
        ),
    ]
